### ISSUE TITLE
佬，想请求0-4的图片类型，应该怎么填啊

### ISSUE THREAD

**Issue by weizid** [GardenHamster/LoliSuki#1]
纯小白。。。
![QQ截图20221012195158](https://user-images.githubusercontent.com/37445278/195335879-eb3c8e69-f1f5-49b8-bd11-f01c59d6810f.png)
![QQ截图20221012195348](https://user-images.githubusercontent.com/37445278/195336027-7d457064-785a-4d34-9dea-e7801ec87908.png)

**Comment by GardenHamster** [comment]
level参数传入0-4就行，具体怎么传建议联系这个api插件的原作者或者看看他的文档
